name = "Sort Inventory"
description = "Sorts inventory by weapons, equipment, food, etc when you press z. Ctrl+z changes the sorting method. Shift+z toggles whether the first 1-2 slots are sorted. (See Workshop page for v1.2 updates!)"
author = "Brody"
version = "1.21"
forumthread = ""
api_version = 6
icon_atlas = "modicon.xml"
icon = "modicon.tex"
restart_required = false
dont_starve_compatible = true
reign_of_giants_compatible = true
shipwrecked_compatible = true